version: 2.1

executors:
  builder:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    working_directory: /tmp/workspace

jobs:
  build:
    executor: builder
    steps:
      - checkout

      - restore_cache:
          keys:
            - xor-filter-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}
            - xor-filter-dependencies-{{ .Branch }}-
            - xor-filter-dependencies-

      - run:
          name: Resolve dependencies
          command: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: xor-filter-dependencies-{{ .Branch }}-{{ checksum "build.gradle" }}

      - run:
          name: Test
          command: ./gradlew test --stacktrace

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results
